## Numpy Introduction

In [9]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [10]:
#install package

In [11]:
#import numpy
import numpy as np

#### Creating Array

In [13]:
np.array([1,2,3])

array([1, 2, 3])

In [14]:
np.zeros(6)


array([0., 0., 0., 0., 0., 0.])

In [15]:
np.ones(6)


array([1., 1., 1., 1., 1., 1.])

In [16]:
np.empty(6)


array([1., 1., 1., 1., 1., 1.])

In [17]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [18]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

#### Add, Remove, and Sort

In [19]:
arr = np.array([1,2,3,4,5,6,7,8])
np.append(arr, [1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [20]:
np.delete( arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [21]:
arr = np.array([2,1,5,3,7,4,6,8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

#### Shape and Size

In [24]:
array_example = np.array([[[0,1,2,3],
                          [4,5,6,7]],
                          
                         [[0,1,2,3],
                         [4,5,6,7]],
                          
                         [[0,1,2,3],
                         [4,5,6,7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [25]:
array_example.ndim

3

In [26]:
array_example.size

24

In [28]:
array_example.shape

(3, 2, 4)

#### Reshape

In [29]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [31]:
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [32]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

## Convert 1D to 2D

In [33]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [34]:
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [35]:
# you can convert a 1D array to a row vector by inserting an axis along the first dimention

row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [36]:
# for a column vector, you can insert an axis along the second dimention
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [37]:
# menggunakan np.expand_dims

a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [39]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [41]:
c = np.expand_dims(a , axis=0)
c.shape

(1, 6)

#### Indexing and Slicing

In [42]:
data = np.array([1,2,3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [43]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [44]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [46]:
c = a[(a>2) & (a<11)]
c

array([ 3,  4,  5,  6,  7,  8,  9, 10])

#### Creating Array from Existing Data

In [47]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [48]:
a_1 = np.array([[1,1],
               [2,2]])

a_2 = np.array([[3,3],
               [4,4]])

np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [49]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [51]:
arrsplit = np.array([[1,2,3,4,5,6,7,8,9,10,11,12],
                    [13,14,15,16,17,18,19,20,21,22,23,24]])

In [52]:
np.hsplit(arrsplit, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

## Basic Array Operations

In [53]:
a = np.array([1,2,3,4])

a.sum()

10

In [54]:
b = np.array([[1,1],
             [2,2]])

b.sum(axis=0)

array([3, 3])

In [55]:
b.sum(axis=1)

array([2, 4])

#### More Array Operations

In [58]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [59]:
print(A.sum())
print(A.min())
print(A.min(axis=0))
print(A.max())
print(A.max(axis=1))
print(A.std())

4.8595784
0.05093587
[0.12697628 0.05093587 0.26590556 0.5510652 ]
0.82485143
[0.5510652  0.55645993 0.82485143]
0.21392120766089617


## Creating Matrices

In [64]:
print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.66516291 0.35794696]
 [0.72052092 0.97184968]
 [0.46336689 0.44690237]]


#### Dot Product

In [65]:
a_1 = np.array([[1,2,3], [4,5,6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7,8],[9,10],[11,12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [66]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

In [67]:
data = np.array([[1,2],[3,4],[5,6]])

print(data)
print(data[0])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2, 1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


#### Matrix Aggregation

In [68]:
print(data)

print(data.max())
print(data.min())
print(data.sum())

[[1 2]
 [3 4]
 [5 6]]
6
1
21


In [69]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


#### Transposing and Reshaping

In [70]:
print(data)
print(data.T)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [71]:
data_col = np.array([[1,2,3,4,5,6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [72]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

## N-Dimensional Array

In [74]:
ndarr = np.array([[[1,2], [3,4]],
                 [[5,6], [7,8]]])

print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
